Python packages: need to use jupyter_client version 5.3.4 (#2423).
At least, we cannot use the latest version which is currently version 6.1.7 and which would normally be installed (since jupyter_client is required by another package). So, here, we force the installation of a version that we know works.

Indeed, if we were to use version 6.1.7, then to run OpenCOR would result in the following errors (on Linux):

Traceback (most recent call last):
  File "", line 59, in create_ipython_widget
  File "", line 34, in __init__
  File "/home/alan/OpenCOR/build/python/lib/python3.7/site-packages/qtconsole/inprocess.py", line 77, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "/home/alan/OpenCOR/build/python/lib/python3.7/site-packages/ipykernel/inprocess/client.py", line 64, in start_channels
    super(InProcessKernelClient, self).start_channels()
  File "/home/alan/OpenCOR/build/python/lib/python3.7/site-packages/jupyter_client/client.py", line 118, in start_channels
    self.control_channel.start()
AttributeError: QObject has no attribute named 'control_channel'
Segmentation fault (core dumped)

Note that with jupyter_client version 5.3.4, we don't get the "control_channel" issue anymore. However, we are still getting the segmentation fault. So, still need to fix something else.